var copilotCommands = [
  "workbench.panel.chat.view.copilot.focus",
  "workbench.panel.chat.view.copilot.resetViewLocation",
  "workbench.action.chat.copilot.history",
  "workbench.action.chat.copilot.newChat",
  "workbench.action.chat.copilot.openInEditor",
  "workbench.action.chat.copilot.openInWindow",
  "workbench.action.openChat.copilot",
  "workbench.action.openQuickChat.copilot",
  "workbench.panel.chat.view.copilot.toggleVisibility",
  "workbench.panel.chat.view.copilot.removeView",
  "github.copilot.toggleCopilot",
  "github.copilot.toggleStatusMenu",
  "github.copilot.collectDiagnostics",
  "github.copilot.sendFeedback",
  "github.copilot.openDocs",
  "github.copilot.openLogs",
  "github.copilot.signIn",
  "workbench.action.output.show.GitHub.copilot.GitHub Copilot",
  "workbench.action.output.show.GitHub.copilot-chat.GitHub Copilot Chat",
  "workbench.action.output.show.extension-output-GitHub.copilot-#1-GitHub Copilot Log",
  "github.copilot.generate",
  "github.copilot.acceptCursorPanelSolution",
  "github.copilot.previousPanelSolution",
  "github.copilot.nextPanelSolution",
  "github.copilot.openPanelForRange",
  "github.copilot.acceptPanelSolution",
  "github.copilot.interactiveSession.feedback",
  "github.copilot.ghpr.applySuggestion",
  "github.copilot.debug.workbenchState",
  "github.copilot.terminal.explainTerminalSelection",
  "github.copilot.terminal.explainTerminalSelectionContextMenu",
  "github.copilot.terminal.explainTerminalLastCommand",
  "github.copilot.terminal.suggestCommand",
  "github.copilot.terminal.generateCommitMessage",
  "github.copilot.git.generateCommitMessage",
  "github.copilot.devcontainer.generateDevContainerConfig",
  "github.copilot.interactiveEditor.explain",
  "github.copilot.interactiveEditor.generate",
  "github.copilot.interactiveEditor.generateDocs",
  "github.copilot.interactiveEditor.generateTests",
  "github.copilot.interactiveEditor.fix",
  "github.copilot.newNotebook",
  "github.copilot.createProject",
  "github.copilot.debug.contentExclusions",
  "github.copilot.executeSearch",
  "chrome.github.copilot.helloWorld",
];
